package com.epam.hospital.constant.web;

public final class RequestParameters {
    public static final String LOGIN = "login";
    public static final String PASSWORD = "password";
    public static final String FIRST_NAME = "firstName";
    public static final String LAST_NAME = "lastName";
    public static final String DOCTOR = "doctor";
    public static final String USER_ROLE_ID = "role_id";
    public static final String CLASSIFICATION = "classification";
    public static final String SPECIALIZATION = "specialization";
    public static final String WORK_EXPERIENCE = "workExperience";
    public static final String PHONE_NUMBER = "phoneNumber";
    public static final String COMMAND = "command";
    public static final String AGE = "age";
    public static final String SEX = "sex";
    public static final String SPARE_PHONE_NUMBER = "sparePhoneNumber";
    public static final String CHAMBER_ID = "chamberId";
    public static final String CHAMBER_TYPE_ID = "chamberTypeId";
    public static final String IS_ONLINE = "isOnline";
    public static final String SYMPTOMS = "symptoms";
    public static final String INSTRUCTION = "instructions";
    public static final String DRUG = "drug";
    public static final String DISEASE = "disease";
    public static final String DESCRIPTION = "description";
    public static final String DOSE = "dose";
    public static final String CONSULTATION_ID = "id";
    public static final String HOSPITALIZATION_ID = "id";
    public static final String DATE_IN = "dateIn";
    public static final String DATE_OUT = "dateOut";
    public static final String DATE = "date";
    public final static String DURATION = "duration";
    public final static String ID = "id";
    public final static String PAGE = "page";
    public final static String PRICE = "price";
    public final static String LOCALE = "locale";
    public final static String NAME = "name";
    public static final String CONTENT = "content";
    public static final String CONTENT_SIZE = "content-size";
    public static final String CURRENT_PAGE = "current-page";
    public static final String PARENT_ID = "parent_id";
}
